/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'on-tertiary-container': '#fffbff',
        'surface-bright': '#f8f9ff',
        'primary-fixed': '#d8e2ff',
        'on-primary-container': '#fefcff',
        'primary-fixed-dim': '#adc6ff',
        'tertiary': '#825100',
        'surface-container-high': '#dce9ff',
        'inverse-on-surface': '#eaf1ff',
        'on-secondary-fixed': '#00201c',
        'outline-variant': '#c2c6d6',
        'tertiary-fixed': '#ffddb8',
        'surface-dim': '#cbdbf5',
        'surface-container-low': '#eff4ff',
        'on-tertiary-fixed-variant': '#653e00',
        'secondary-fixed-dim': '#4fdbc8',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#2170e4',
        'on-error-container': '#93000a',
        'inverse-primary': '#adc6ff',
        'outline': '#727785',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#005048',
        'secondary': '#006b5f',
        'on-primary-fixed': '#001a42',
        'background': '#f8f9ff',
        'secondary-container': '#6df5e1',
        'on-background': '#0b1c30',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#424754',
        'tertiary-fixed-dim': '#ffb95f',
        'surface-variant': '#d3e4fe',
        'surface-tint': '#005ac2',
        'inverse-surface': '#213145',
        'tertiary-container': '#a36700',
        'on-error': '#ffffff',
        'surface-container': '#e5eeff',
        'surface': '#f8f9ff',
        'primary': '#0058be',
        'secondary-fixed': '#71f8e4',
        'error': '#ba1a1a',
        'on-tertiary-fixed': '#2a1700',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#006f64',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#004395',
        'surface-container-highest': '#d3e4fe',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '8px',
        gutter: '12px',
        lg: '24px',
        'container-margin': '16px',
        md: '16px',
        sm: '12px',
        xl: '32px',
        base: '4px',
      },
      fontFamily: {
        'headline-md': ['Plus Jakarta Sans'],
        'body-lg': ['Be Vietnam Pro'],
        'body-md': ['Be Vietnam Pro'],
        'label-lg': ['Be Vietnam Pro'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'label-sm': ['Be Vietnam Pro'],
        'display-lg': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['22px', { lineHeight: '30px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
